### ISSUE TITLE
Магическое число 20

### ISSUE THREAD

**Issue by ilyaevseev** [Pin4uck/HelloWorld#10]
https://github.com/Pin4uck/HelloWorld/blob/ecf343938c6a7b9869b2ffb7aa8b2579ad16cb5c/currency_copy.py#L17

* Все магические числа должны быть описаны именованными константами в начале файла.
* В идеале - сделаны настраиваемыми, но это пока можно отложить.
* 20 секунд - это слишком мало для кэширования, имеет смысл поставить хотя бы 3600, т.е. один час.
* Хотя для теста 20 секунд лучше, чем 3600
* Лишний аргумент, чтобы сделать значение настраиваемым

**Comment by Pin4uck** [comment]
исправлено

**Comment by ilyaevseev** [comment]
В ветке "main" пока не исправлено. Сделайте merge из ветки с исправлением в main.

В issue обязательно нужна ссылка на исправляющий commit. Если в commit message указать номер issue, то issue закроется автоматически, и ссылка на commit будет вставлена в issue также автоматически.
