### ISSUE TITLE
Возврат ошибки

### ISSUE THREAD

**Issue by ilyaevseev** [Pin4uck/HelloWorld#11]
https://github.com/Pin4uck/HelloWorld/blob/ecf343938c6a7b9869b2ffb7aa8b2579ad16cb5c/currency_copy.py#L41

### Плохо:

```
result = "..."
return result
```

### Лучше:

```
return "..."
```

### Правильнее:

```
return None # ..а сообщение об ошибке пусть пишет вызывающая программа
```

**Comment by Pin4uck** [comment]
Решено в currency.py
