### ISSUE TITLE
Нужны кавычки

### ISSUE THREAD

**Issue by ilyaevseev** [Pin4uck/HelloWorld#12]
https://github.com/Pin4uck/HelloWorld/blob/9a199adcafa66d8e7b79329a2d89dea2e73e8579/currency_copynew.py#L19

### Не заработает:
```
WHERE Abbreviation = {}
```
### Заработает, но плохо:
```
WHERE Abbreviation = '{}'
```
### Правильно:

* использовать placeholders, чтобы защититься от [SQL injection](https://ru.wikipedia.org/wiki/Внедрение_SQL-кода) через значения с кавычками
* см. "placeholders" в https://docs.python.org/3/library/sqlite3.html

**Comment by Pin4uck** [comment]
Это не помогает я пробовал, и сейчас еще раз попробовал

**Comment by Pin4uck** [comment]
решено
