### ISSUE TITLE
Except охватывает только открытие базы

### ISSUE THREAD

**Issue by ilyaevseev** [Pin4uck/HelloWorld#14]
https://github.com/Pin4uck/HelloWorld/blob/2e18a5723d6dff080b1b8b318da97a2f87d656a2/currency_copynew.py#L8

Ниже идёт создание таблиц, и оно тоже может закончиться с ошибкой.  
Например, если файл доступен только на чтение.

**Comment by Pin4uck** [comment]
Решено в currency.py

**Comment by ilyaevseev** [comment]
Должна быть ссылка на исправляющий коммит!

Если коммит содержит номер исправляемой issue, ссылка вставится автоматически.
