### ISSUE TITLE
В insert лучше явно перечислять столбцы

### ISSUE THREAD

**Issue by ilyaevseev** [Pin4uck/HelloWorld#16]
https://github.com/Pin4uck/HelloWorld/blob/2e18a5723d6dff080b1b8b318da97a2f87d656a2/currency_copynew.py#L27

### Плохо:

```
insert into table_name values(v1,v2,v3);
```

Хорошо:

```
insert into table_name(col1,col2,col3) values(v1,v2,v3);
```

**Comment by Pin4uck** [comment]
Решено
https://github.com/Pin4uck/Bot_Testik/blob/987a916b42c612432963a39933127e3b13da6f2e/currency_try_except.py#L27

**Comment by ilyaevseev** [comment]
Уже лучше, со ссылкой.

Но ссылку лучше было сделать в относительном виде вместо абсолютного:

[../../Bot_Testik/blob/987a916b42c612432963a39933127e3b13da6f2e/currency_try_except.py#L27](../../Bot_Testik/blob/987a916b42c612432963a39933127e3b13da6f2e/currency_try_except.py#L27)
