### ISSUE TITLE
Лишний SELECT

### ISSUE THREAD

**Issue by ilyaevseev** [Pin4uck/HelloWorld#17]
https://github.com/Pin4uck/HelloWorld/blob/2e18a5723d6dff080b1b8b318da97a2f87d656a2/currency_copynew.py#L30

Зачем читать из базы данные, которые мы только что в неё записали?  
Не проще сразу вернуть `ofcrate` ?

**Comment by Pin4uck** [comment]
Решено
https://github.com/Pin4uck/HelloWorld/blob/a9bffc6b4304285ac9f12f7e8aa45edf128698f4/currency_copynew.py#L29
