### ISSUE TITLE
Невнятный результат

### ISSUE THREAD

**Issue by ilyaevseev** [Pin4uck/HelloWorld#18]
https://github.com/Pin4uck/HelloWorld/blob/2e18a5723d6dff080b1b8b318da97a2f87d656a2/currency_copynew.py#L44

### Совсем плохо:
```
result = 'Ошибка приложения'
return result
```

### Чуть лучше (одна строка вместо двух):
```
return 'Ошибка приложения'
```

### Оптимально - не ловить exception от последней попытки:

* свежие данные в базе = нет или ошибка, которую ловим внутри функции и переходим к чтению из сети
* чтение из сети = нет или ошибка, которую ловим внутри функции и переходим к повторному чтению из базы
* данные в базе = нет или ошибка, которую НЕ ловим внутри функции, потому что функция уже не имеет вариантов для её обработки - поэтому её ловит вызывающая программа и отвечает пользователю

**Comment by Pin4uck** [comment]
Решено в currency.py
