### ISSUE TITLE
В таблице валют нужно поле с временем обновления записи

### ISSUE THREAD

**Issue by ilyaevseev** [Pin4uck/HelloWorld#3]
https://github.com/Pin4uck/HelloWorld/blob/958ff78b0d8ed381f8e98b2107172fd43bbd9673/SQLtest.py#L19

### Примерное описание:

```
create table ... (
   ...
   last_updated TIMESTAMP default (strftime('%s')),
   ...
);
```

### Пояснения:

* default = при insert его не надо будет указывать явно
* strftime = функция показа времени
* "%s" = показ времени в секундах от 1 января 1970 (т.н. unix timestamp)
* см. https://stackoverflow.com/a/11556717/2743554

### При select:

```
select rate
from currencies
where currency_name = "имя_валюты"
and (strftime('%s') - last_updated <= максимально_допустимый_возраст_всекундах);
```

**Comment by Pin4uck** [comment]
# Правильно поле с временем вставил?
import sqlite3


conn = sqlite3.connect('database.db')
curs = conn.cursor()


curs.execute('''CREATE TABLE IF NOT EXISTS ccy (
                id INTEGER NOT NULL PRIMARY KEY,
                last_updated timestamp default (strftime('%s', 'now')),
                Abbreviation TEXT UNIQUE NOT NULL ,
                Rate FLOAT NOT NULL)'''
             )


a = input('''Введите интересующую вас валюту, например: 'USD', 'EUR', 'RUB' ''')
curs.execute('''SELECT Rate FROM ccy 
WHERE Abbreviation = {} and (strftime('%s') - last_updated <= 10)'''.format(a))
row = curs.fetchall()
if not row:
    curs.execute('INSERT INTO ccy VALUES(1, strftime("%s"), "usd", 2.5)')
    curs.execute('INSERT INTO ccy VALUES(2, strftime("%s"), "eur", 3)')
    curs.execute('INSERT INTO ccy VALUES(3, strftime("%s"), "rub", 3.5)')
    conn.commit()
    curs.execute('''SELECT Rate FROM ccy 
    WHERE Abbreviation = {} '''.format(a))
    row = curs.fetchall()
    print(row[0][0])
    print('hel')
else:
    print(row[0][0])

**Comment by ilyaevseev** [comment]
Попробуйте отредактировать свой комментарий, включив разметку кода.

См. https://guides.github.com/features/mastering-markdown/ => Examples => Code

Помните про Preview и про кнопки над окном редактирования.

**Comment by ilyaevseev** [comment]
### Попробуйте проверить самостоятельно:

* запустите sqlite3
* введите команду создания таблицы: `CREATE TABLE ccy( описания_стобцов );`
* добавьте несколько записей:
  ```
  insert into ccy(Abbreviation, Rate) values('aa',123),('bb',234),('cc',456);
  ```
* посмотрите результат:
  ```
  select * from ccy;
  ```

**Comment by Pin4uck** [comment]
Нет, так я проверял - вроде все работает. Я просто не уверен все ли правильно, поэтому спросил правильно ли все)

**Comment by Pin4uck** [comment]
ну правда как работает, наполовину так скажем, когда время выходит и нужно обновить запись в базе, то выдает ошибку. я так понимаю из-за одинакового названия. То есть если я правильно понимаю, программа хочет добавить запись новую не удаляя старую, а одинаковую запись добавить нельзя из-за ограничения. То  есть нужно сделать так, чтобы она прога не добавляла а обновляла запись?
Ошибка которая выскакивает вот:
Traceback (most recent call last):
  File "<input>", line 21, in <module>
sqlite3.IntegrityError: UNIQUE constraint failed: ccy.id

**Comment by ilyaevseev** [comment]
Это называется UPSERT, от UPDATE + INSERT:  
https://www.sqlite.org/lang_UPSERT.html

Т.е. пытаемся вставить запись как новую, но в случае конфликта ключей с уже существующей - обновляем существующую.

**Comment by Pin4uck** [comment]
### Вроде что-то получилось
```python
import sqlite3


conn = sqlite3.connect('currency.db')
curs = conn.cursor()


curs.execute('''CREATE TABLE IF NOT EXISTS ccy (
                id INTEGER NOT NULL PRIMARY KEY,
                last_updated timestamp default (strftime('%s', 'now')),
                Abbreviation TEXT UNIQUE NOT NULL ,
                Rate FLOAT NOT NULL)'''
             )


a = input('''Введите интересующую вас валюту, например: 'USD', 'EUR', 'RUB' ''')
curs.execute('''SELECT Rate FROM ccy 
WHERE Abbreviation = {} and (strftime('%s') - last_updated <= 10)'''.format(a))
row = curs.fetchall()
if not row:
    curs.execute('''INSERT INTO ccy VALUES(1, strftime("%s"), "usd", 2.5)
    on conflict (id) do update set Rate=excluded.Rate, last_updated = excluded.last_updated''')
    curs.execute('''INSERT INTO ccy VALUES(2, strftime("%s"), "eur", 3)
    on conflict (id) do update set Rate=excluded.Rate, last_updated = excluded.last_updated''')
    curs.execute('''INSERT INTO ccy VALUES(3, strftime("%s"), "rub", 3.5)
    on conflict(id) do update set Rate = excluded.Rate, last_updated = excluded.last_updated''')
    conn.commit()
    curs.execute('''SELECT Rate FROM ccy 
    WHERE Abbreviation = {} '''.format(a))
    row = curs.fetchall()
    print(row[0][0])
    print('проверка')
else:
    print(row[0][0])
```

**Comment by Pin4uck** [comment]
Решено

**Comment by ilyaevseev** [comment]
Имеет смысл в закрывающем комментарии делать ссылку на исправивший коммит.
