### ISSUE TITLE
Проверка результатов

### ISSUE THREAD

**Issue by ilyaevseev** [Pin4uck/HelloWorld#6]
https://github.com/Pin4uck/HelloWorld/blob/958ff78b0d8ed381f8e98b2107172fd43bbd9673/requirements.py#L10

```
rows = cur.fetchall()
if not rows:
    ...
else:
    row = rows[0]
    ...
```

**Comment by Pin4uck** [comment]
Этот пункт в currency.py тоже выполнен правильно?

**Comment by ilyaevseev** [comment]
В currency.py пока неправильно, в комментариях к #7 уже правильно.
