### ISSUE TITLE
Функция должна получать имя валюты параметром, а не запрашивать с консоли

### ISSUE THREAD

**Issue by ilyaevseev** [Pin4uck/HelloWorld#8]
https://github.com/Pin4uck/HelloWorld/blob/ecf343938c6a7b9869b2ffb7aa8b2579ad16cb5c/currency_copy.py#L15

* Запрос из консоли должен быть в главной программе, а не внутри функции.
* Функция должна получать значение от главной программы как параметр.
* В телеграм-боте функция должна вызываться со значением, полученным от пользователя.

**Comment by Pin4uck** [comment]
Решено

**Comment by ilyaevseev** [comment]
Где ссылка на коммит??
