### ISSUE TITLE
Внутри рабочей функции не должно быть заполнения таблицы тестовыми записями

### ISSUE THREAD

**Issue by ilyaevseev** [Pin4uck/HelloWorld#9]
https://github.com/Pin4uck/HelloWorld/blob/ecf343938c6a7b9869b2ffb7aa8b2579ad16cb5c/currency_copy.py#L22

Заполнение таблицы тестовыми записями надо вынести в отдельный SQL-файл.

**Comment by Pin4uck** [comment]
решено

**Comment by ilyaevseev** [comment]
Без ссылки на коммит не поверю))
